name: connect_chain
description: "Bulk-Buying B2B Platform"
publish_to: "none"  # Remove if publishing to pub.dev

# Versioning (major.minor.patch+build)
version: 1.0.5+1

environment:
  sdk: ^3.6.0-149.3.beta  

dependencies:
  # State Management
  flutter_bloc: ^9.1.0       
  provider: ^6.1.4

  # DI
  get_it: ^8.0.3    

  # UI Components
  cupertino_icons: ^1.0.8    
  flutter_svg: ^2.0.17       
  cached_network_image: ^3.4.1  
  photo_view: ^0.15.0        
  shimmer: ^3.0.0            
  smooth_page_indicator: ^1.2.1 
  dotted_border: ^2.1.0      
  fl_chart: ^0.70.2          

  # Networking
  dio: ^5.8.0+1              
  pretty_dio_logger: ^1.4.0  
  http_parser: ^4.1.2        

  # Localization
  easy_localization: ^3.0.7+1 
  intl: ^0.19.0             

  # Storage
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4

  # Device Features
  image_picker: ^1.1.2
  firebase_core: ^3.12.1

  # Utilities
  flutter_screenutil: ^5.9.3 
  meta: ^1.9.1               
  mime: ^2.0.0               
  freezed_annotation: ^2.4.4 

  # Core Flutter
  flutter:
    sdk: flutter

dev_dependencies:
  # Code Generation
  build_runner: ^2.4.13      
  freezed: ^2.5.7            

  # Testing & Quality
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0      

  # Build Process
  flutter_native_splash: ^2.4.4

flutter:
  uses-material-design: true  

  # Asset management
  assets:
    - assets/images/         
    - assets/svgs/           
    - assets/translations/   

  # Font configurations
  fonts:
    - family: cairo
      fonts:
        - asset: assets/fonts/cairo/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/cairo/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/cairo/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/cairo/Cairo-Bold.ttf
          weight: 700
    - family: tajawal
      fonts:
        - asset: assets/fonts/tajawal/Tajawal-Regular.ttf
          weight: 400
        - asset: assets/fonts/tajawal/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/fonts/tajawal/Tajawal-Bold.ttf
          weight: 700