default_platform(:android)

platform :android do
  desc "Lane for Android Firebase Distribution"
  lane :distribute_to_firebase do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
    release = firebase_app_distribution(
            app: "1:287776857436:android:bb6740a8c9021a70b63599",
            testers: "amrmmohamed00@gmail.com",
            release_notes: "Lots of amazing new features to test out!",
            firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
            android_artifact_type: "APK",
            android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk"
        )
  end
end
